from turtle import *
setup()

speed('fastest')
pen = 'black'
width_card = 120
height_card = 200

number = 20
def basketball():     
    # Draw Card Background
    write(number)
    pencolor(pen)
    width(2)
    pd()
    fillcolor('light blue')
    begin_fill()
    for cards in range(2):
            forward(width_card//2)
            circle(-20,90)
            forward(height_card)
            circle(-20,90)
            forward(width_card//2)
    end_fill()
    pu()
    
    #Draw basketball
    fillcolor('orange') 
    right(180)
    forward(75)
    left(90)
    forward(100)

    begin_fill()
    pd()
    circle(75)
    end_fill()

    left(90)
    forward(150)

    left(100)
    forward(20)
    left(40)
    forward(10)
    left(10)
    forward(20)
    left(10)
    forward(20)
    left(10)
    forward(20)
    left(10)
    forward(20)
    left(10)
    forward(20)
    left(15)
    forward(20)
    left(15)
    forward(20)
    left(10)
    forward(10)
    
    pu()
    left(43)
    forward(35)
    pd()

    setheading(-40)
    #left(40)
    forward(10)
    left(10)
    forward(20)
    left(10)
    forward(20)
    left(10)
    forward(20)
    left(10)
    forward(20)
    left(10)
    forward(20)
    left(15)
    forward(20)
    left(15)
    forward(20)
    left(10)
    forward(10)
    pu()
    home()

def tennisball():
    # Draw Card Background
    pencolor(pen)
    width(2)
    pd()
    fillcolor('forest green')
    begin_fill()
    for cards in range(2):
            forward(width_card//2)
            circle(-20,90)
            forward(height_card)
            circle(-20,90)
            forward(width_card//2)
    end_fill()
    pu()
    
    #Draw tennisball
    fillcolor('lawn green') 
    right(180)
    forward(75)
    left(90)
    forward(100)

    begin_fill()
    pd()
    circle(75)
    end_fill()

    pu()
    circle(75,60)
    pd()
    pencolor('snow')
    width(4)
    left(65)
    forward(10)
    left(20)
    forward(15)
    left(20)
    forward(15)
    left(20)
    forward(15)
    left(20)
    forward(15)
    left(20)
    forward(15)
    right(20)
    forward(10)
    right(25)
    forward(10)
    right(25)
    forward(15)
    right(25)
    forward(15)
    right(25)
    forward(15)
    right(20)
    forward(15)
    right(20)
    forward(15)
    right(20)
    forward(15)
    right(25)
    forward(15)
    right(25)
    forward(15)
    left(25)
    forward(15)
    left(25)
    forward(15)
    left(25)
    forward(15)
    left(15)
    forward(4)
    pu()
    pencolor('black')
    width(0)
    home()
        
def bowlingball():
    # Draw Card Background
    pencolor(pen)
    width(2)
    pd()
    fillcolor('cyan')
    begin_fill()
    for cards in range(2):
            forward(width_card//2)
            circle(-20,90)
            forward(height_card)
            circle(-20,90)
            forward(width_card//2)
    end_fill()
    pu()
    
    #Draw bowlingball
    fillcolor('dodger blue') 
    right(180)
    forward(75)
    left(90)
    forward(100)

    begin_fill()
    pd()
    circle(75)
    end_fill()
    pu()

    left(90)
    forward(60)
    left(90)
    forward(20)
    pd()
    dot(20)
    pu()

    right(90)
    forward(30)
    pd()
    dot(20)
    pu()

    right(180)
    forward(15)
    left(90)
    forward(45)
    pd()
    dot(25)
    pu()
    home()
        
def soccerball():
    # Draw Card Background
    pencolor(pen)
    width(2)
    pd()
    fillcolor('chartreuse')
    begin_fill()
    for cards in range(2):
            forward(width_card//2)
            circle(-20,90)
            forward(height_card)
            circle(-20,90)
            forward(width_card//2)
    end_fill()
    pu()
    
    #Draw soccerball
    fillcolor('ghost white') 
    right(180)
    forward(75)
    left(90)
    forward(100)

    begin_fill()
    pd()
    circle(75)
    end_fill()
    pu()

    circle(75,35)

    pd()
    fillcolor('black')
    begin_fill()
    left(93)
    forward(18)
    right(75)
    forward(45)
    right(80)
    forward(15)
    right(70)
    circle(-50,48)
    end_fill()
    right(48)
    forward(35)
    left(40)
    forward(20)

    begin_fill()
    left(65)
    forward(20)
    right(85)
    circle(-52,60)
    right(75)
    forward(18)
    end_fill()

    left(45)
    forward(20)
    left(45)
    forward(22)

    begin_fill()
    left(60)
    forward(17)
    right(93)
    circle(-55,63)
    right(90)
    forward(18)
    end_fill()

    left(50)
    forward(20)
    left(50)
    forward(20)

    begin_fill()
    left(70)
    forward(22)
    right(93)
    circle(-55,63)
    right(90)
    forward(20)
    end_fill()

    left(65)
    forward(15)
    left(45)
    forward(15)

    begin_fill()
    left(70)
    forward(20)
    right(100)
    circle(-53,50)
    right(90)
    forward(15)
    end_fill()

    left(45)
    forward(15)
    left(90)
    forward(20)

    right(180)
    forward(20)
    left(45)
    forward(20)
    
    begin_fill()
    left(60)
    forward(25)
    right(80)
    forward(30)
    right(70)
    forward(30)
    right(73)
    forward(28)
    right(77)
    forward(28)
    end_fill()

    right(180)
    forward(25)
    right(75)
    forward(17)

    right(180)
    forward(17)
    right(35)
    forward(30)
    right(53)
    forward(15)

    right(180)
    forward(15)
    right(45)
    forward(32)
    right(71)
    forward(25)
    right(180)
    forward(25)
    right(40)
    forward(30)
    right(60)
    forward(25)
    pu()
    home()

def joker():
    # Draw Card Background
    pencolor(pen)
    width(2)
    pd()
    fillcolor('firebrick')
    begin_fill()
    for cards in range(2):
            forward(width_card//2)
            circle(-20,90)
            forward(height_card)
            circle(-20,90)
            forward(width_card//2)
    end_fill()
    pu()

    right(180)
    forward(75)
    left(90)
    forward(220)
    left(48)
    forward(10)
    pd()

    fillcolor('white')
    begin_fill()
    forward(5)
    left(35)
    forward(5)
    left(25)
    forward(5)
    left(25)
    forward(5)
    left(35)
    forward(5)
    left(35)
    forward(5)
    left(25)
    forward(15)
    left(35)
    forward(5)
    left(35)
    forward(5)
    left(15)
    forward(5)
    left(25)
    forward(5)
    left(35)
    forward(5)
    left(35)
    forward(9)
    end_fill()

    pu()
    left(80)
    forward(15)
    left(21)
    pd()
    pencolor('black')
    fillcolor('black')
    begin_fill()
    forward(100)
    left(90)
    forward(10)
    left(90)
    forward(100)
    right(40)
    forward(2)
    left(60)
    forward(2)
    left(35)
    forward(2)
    left(15)
    forward(2)
    left(15)
    forward(2)
    left(10)
    forward(3)
    left(15)
    forward(2)
    left(35)
    forward(2)
    left(15)
    forward(2)
    left(25)
    forward(2)
    end_fill()

    pu()
    pencolor('black')
    fillcolor('white')
    begin_fill()
    right(4.5)
    forward(100)
    #pencolor(pen)
    pd()
    forward(50)
    right(20)
    forward(25)
    left(20)
    forward(60)
    left(90)

    right(60)
    forward(2)
    left(40)
    forward(5)
    left(20)
    forward(9)
    left(10)
    forward(5)
    left(5)
    forward(5)
    left(20)
    forward(3)
    left(20)
    forward(3)
    left(35)
    forward(55)
    left(20)
    forward(25)
    right(20)
    forward(52)
    left(90)
    forward(12)
    end_fill()
    pu()
    home()



basketball()
# tennisball()
# bowlingball()
# soccerball()
#joker()

hideturtle()
done()